name: Deploy Website to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Configure AWS credentials from GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t devops-dynamic-website .
          docker tag devops-dynamic-website:latest <your-ecr-repository-url>:latest
          docker push <your-ecr-repository-url>:latest

      - name: Deploy with AWS CloudFormation
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/website.yaml \
            --stack-name devops-dynamic-website-stack \
            --capabilities CAPABILITY_NAMED_IAM

